# Generated by Django 5.2.8 on 2025-12-02 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeros_sorteados', models.JSONField(default=list)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('finalizada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('puntos_totales', models.IntegerField(default=0)),
                ('partidas_jugadas', models.IntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Apuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeros_elegidos', models.JSONField(default=list)),
                ('aciertos', models.IntegerField(default=0)),
                ('puntos_ganados', models.IntegerField(default=0)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keno.jugador')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keno.partida')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('max_jugadores', models.IntegerField(default=10)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas_creadas', to='keno.jugador')),
                ('jugadores', models.ManyToManyField(related_name='salas', to='keno.jugador')),
            ],
        ),
        migrations.AddField(
            model_name='partida',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keno.sala'),
        ),
    ]
